### ISSUE TITLE
cste ?

### ISSUE THREAD

**Issue by alpoler** [sinahmr/DIaM#2]
Dear Sina,

In paper, You use cste as abbreviation; however, there is no explicit form of cste in paper. What does cste refer to ? Thank you for clarification.

**Comment by sinahmr** [comment]
Hi,

In our equations, "Cste" means constant. We meant that there is an additional term, other than the KL divergence, which does not affect the optimization. For example, $- \log(1 + |\mathcal{C}^b| + |\mathcal{C}^n|)$ in equation 7.

$\operatorname{KL}(\widehat{\mathbf{p}} || \mathbf{u}) = \widehat{\mathbf{p}} \cdot \log \frac{\widehat{\mathbf{p}}}{\mathbf{u}} = \widehat{\mathbf{p}} \cdot \log \widehat{\mathbf{p}} - \widehat{\mathbf{p}} \cdot \log \mathbf{u} = \widehat{\mathbf{p}} \cdot \log \widehat{\mathbf{p}} + \log(1 + |\mathcal{C}^b| + |\mathcal{C}^n|)$

Sorry for the confusion.

**Comment by alpoler** [comment]
When Π replaces uniform distribution, cste term equals = p_cap · log Π . Although this is not constant, you keep on referring to it as constant. By the way, thank you for the explanation.

**Comment by sinahmr** [comment]
No problem. I think you are right, thanks for noticing.
