### ISSUE TITLE
How to compare your model with BAM or CAPL?

### ISSUE THREAD

**Issue by liuruixun** [sinahmr/DIaM#4]
Thank you very much for sharing your amazing work!

I would like to build a new GFSS model based on your baseline. As you said in your paper, previous works like BAM and CAPL required potential objects from base classes to be explicitly labeled in the images of the support set S. However, each picture of our support set only have a single label of one novel class (others are all bg). May I ask how you evaluated the performance of BAM and CAPL methods under the above conditions during the comparative experiments.

Thank you.

**Comment by sinahmr** [comment]
Hi,
Thanks for your interest in our work!

As far as I'm concerned, only CAPL requires labelling base classes in the support images (paragraph "Relaxing test-time labeling requirements" in the paper). In our evaluations, we let CAPL use the extra information it required (labels of all classes in the support set).

One common limitation of CAPL and BAM that we talked about in the paper is that they remove images containing novel classes from training, as explained in paragraph "Addressing the presence of novel classes during training" in the paper. 

Hope this helps.
