### ISSUE TITLE
New dataset

### ISSUE THREAD

**Issue by JiaojiaoYe1994** [sinahmr/DIaM#6]
Hi, thank you for your work! I am interested in trying this, is it possible to run on a new dataset? How to formalize it? Thank you

**Comment by sinahmr** [comment]
Hi
Thanks for your interest!

To evaluate the method on a new few-shot benchmark, you first need to have a base model which is trained on your desired set of base classes. To obtain such a base model, please refer to the [Training](https://github.com/sinahmr/DIaM#-training-optional) section of the readme.
After that, you can use the newly trained model and apply our evaluation scripts on it.

**Comment by JiaojiaoYe1994** [comment]
@sinahmr Thank you!

Could you please give more details about the coco annotation, which can be generated by executing the python script data/coco/create_masks.py ( this script uses the [pycocotools](https://github.com/cocodataset/cocoapi/tree/master/PythonAPI/pycocotools) package):
`cd data/coco
python create_masks.py`

Well, where is this `create_masks.py`?

**Comment by sinahmr** [comment]
If you are asking about where the script file is located, well obviously, it is under `data` folder in the `coco` subfolder, [here](https://github.com/sinahmr/DIaM/blob/main/data/coco/create_masks.py).
The script is borrowed from the [RePRI](https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation) repo, maybe you can find more detail about it there.
