### ISSUE TITLE
How the coco_20 folds for train/val list were obtained

### ISSUE THREAD

**Issue by silsgah** [sinahmr/DIaM#7]
Hi researchers, I was looking at recreating the split for the coco_20i folds, I have done that but I wish to know if there is any way of verifying this because PFENet(https://github.com/dvlab-research/PFENet) was not very clear on how the train/val folds 0,1,2,3 were obtained. Any leads would be much appreciated. The train/val lists for COCO contain 82081 and 40137 images respectively but the train/0 count was 21917 and val/0  26052 of which the total is 47969 and this number is way less than the total coco set of images of 82081. This is the total accounting of train/val by the PEFNet paper. 
PFENet list folder accounting analysis
Split 0: train -21917   val 0 -26052  total - 47,942
Split 1: train -41809   val 1 -15305  total - 57,114
Split 2: train -43045   val 2 -13138  total - 56,183
Split 3: train -44614   val 3 -12640  total - 57,254.  

This is what I obtained per the understanding I obtained from the paper and code base
Split 0: Train=68839, Val=10959  
Split 1: Train=75780, Val=4018   
Split 2: Train=75336, Val=4462   
Split 3: Train=75239, Val=4559   
I would appreciate very much how these coco_20i split of images were obtained.

**Comment by sinahmr** [comment]
Hi,
I used the COCO-20^i benchmark as it was used by the previous works, and I'm not sure about how they were originally split, sorry about that.
But, just a point, why do you expect train/0 and val/0 to sum up to 82081?

**Comment by silsgah** [comment]
Because that is the total count of images in the coco train set. Hence I expected the total count to be equal that count.

**Comment by sinahmr** [comment]
But as you mentioned, val/0 is coming from a different set of images (a subset of 40137 images), so I think it has nothing to do with the set of 82081 train images.

**Comment by silsgah** [comment]
Sure, that I agree 100% on that but if you sum up all the training across the split/0,1,2,3 that sum is way over 82 and same applies to Val/0,1,2,3. Do you see what I am talking about.

**Comment by silsgah** [comment]
Again if I think about the criteria of selecting an image for say split 0. An image may have multiple classes in it, if at least a single class in found in the image,it is then put in split0/ training set and same is done to the val set, selecting the images from the training and validation dataset respectively. The image is marked as used hence won't be used again in the split0. Then the next image is examined. This is my thought process on how the split was done.

**Comment by sinahmr** [comment]
In few-shot learning if your novel classes are from the split 0, your training images should not contain those classes. I think the procedure of forming train and val datasets are not the same.
But regardless, since we are dealing with a segmentation dataset and images can contain multiple classes, I don't think you can easily reason about what the sum of different splits should be.

**Comment by silsgah** [comment]
Sure I agree and understand the notion of novel classes in split 0, should not contain the base classes. 
Why do you think the procedure for train and val datasets are not the same, kindly indulge me on this, I seek to understand.

**Comment by sinahmr** [comment]
If for your split 0, base classes are cat and dog and the novel class is horse, to form the training dataset you remove images that contain horse and for your validation dataset you take images that contain horse. 
What I meant was that I do not agree with the part that you said "... same is done to the val set ...".

**Comment by silsgah** [comment]
sure, understand I will look at proceeding with this and let you know. I really want to replicate the split folds. cheers, I will keep you updated once I finish.

**Comment by silsgah** [comment]
@sinahmr I see it now, it is an over kill, the splits and logic in all in the code, no need to try reinvent the wheel.

**Comment by sinahmr** [comment]
Yeah, that makes sense. Closing the issue.
